# Fly.io configuration file
app = "dte-circulars-scraper"
primary_region = "iad"

[build]

[env]
  NODE_ENV = "production"
  PORT = "3009"

[http_service]
  internal_port = 3009
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

  # Increase timeouts for web scraping
  [http_service.concurrency]
    type = "requests"
    hard_limit = 25
    soft_limit = 20

  # Configure HTTP timeouts (much higher than Heroku)
  [http_service.http_options]
    h2_backend = true

[[services]]
  protocol = "tcp"
  internal_port = 3009
  processes = ["app"]

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

  [services.concurrency]
    type = "requests"
    hard_limit = 25
    soft_limit = 20

# Machine configuration
[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 512

# Health check configuration
[checks]
  [checks.health]
    grace_period = "30s"
    interval = "30s"
    method = "GET"
    path = "/"
    port = 3009
    timeout = "10s"
    type = "http"