[build]
  publish = "dist"
  command = "npm run build"
  functions = "netlify-functions"

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"
  PUPPETEER_SKIP_CHROMIUM_DOWNLOAD = "true"
  PUPPETEER_EXECUTABLE_PATH = "/usr/bin/google-chrome-stable"

[functions]
  external_node_modules = ["chrome-aws-lambda"]

# API routes should go to serverless functions
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Redirect all other requests to index.html for SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200