[phases.setup]
aptPkgs = [
  'libglib2.0-0',
  'libnspr4',
  'libnss3',
  'libdbus-1-3',
  'libatk1.0-0',
  'libatk-bridge2.0-0',
  'libatspi2.0-0',
  'libx11-6',
  'libxcomposite1',
  'libxdamage1',
  'libxext6',
  'libxfixes3',
  'libxrandr2',
  'libgbm1',
  'libxcb1',
  'libxkbcommon0',
  'libasound2',
  'libxss1',
  'libgtk-3-0',
  'fonts-liberation'
]

[phases.install]
cmds = [
  'npm ci',
  'npx playwright install chromium',
  'npx playwright install-deps chromium'
]

[phases.build]
cmds = ['npm run build']

[start]
cmd = 'npm start'