services:
  - type: web
    name: dte-circulars-app
    env: node
    plan: free
    buildCommand: npm install && npx playwright install --with-deps chromium && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production